# coding=utf-8


CODE_NOT_EXIST = 10

CODE_PARAMETER_ERR = 20
CODE_UNAVAILABLE = 30

CODE_NO_LOGIN = 40
CODE_NOT_ALLOW = 41
CODE_BANNED = 42

CODE_NEED_CHARGE = 50
CODE_USER_BUSY = 51
CODE_USER_REJECT = 52
CODE_SELF_ROOM = 53
CODE_OTHER_ROOM = 54
CODE_GOLD_CHARGE = 55

CODE_NOT_VIP = 60
CODE_VIP_BUY = 61
CODE_VIP_GIFT = 62
CODE_VIP_BENEFIT = 63
CODE_TIME_OUT = 65

CODE_STORE_FAILED = 70

# game_id 生成失败
FAIL_GEN_ID = 100
# 创建游戏时金币不足
GOLD_NOT_ENOUGH = 101
# 游戏已经开始无法加入
GAME_IS_RUNNING = 102
# 游戏已经达到最大人数限制
REACH_MAX_PLAYER = 103
# 游戏人数不足
PLAYER_NOT_ENOUGH = 104
# 玩家还未准备
PLAYER_NOT_READY = 105
# 当前操作者错误
CURRENT_PLAYER_ERROR = 106
# 飞机移动错误
PLANE_MOVE_ERROR = 107
# 游戏不存在
GAME_NOT_EXIST = 108




